name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Checkout output branch if exists
        run: |
          git fetch origin output || echo "No output branch yet"
          git checkout -b output origin/output || git checkout --orphan output
          mkdir -p old_output
          cp -r . old_output || true

      - name: Restore previous files to dist
        run: |
          mkdir -p dist
          cp -r old_output/* dist/ || echo "No previous files to copy"

      - name: Push dist/ to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          allow_empty_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
