name: Generate snake animation

on:
  schedule: # setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Keep existing files (fetch output branch)
        run: |
          git fetch origin output:output || echo "No output branch yet"
          mkdir -p old_output
          git --work-tree=old_output checkout output || echo "Nothing to restore"

      - name: Copy existing files except snake.svg
        run: |
          mkdir -p dist
          cp -r old_output/* dist/ || true
          cp dist/snake.svg dist/snake.svg  # pastikan snake terbaru ditimpa

      - name: Push dist/ to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          allow_empty_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
